if(MARK_SHOT_LINUX AND PipeWire_FOUND)
    target_link_libraries(mark-shot PRIVATE PkgConfig::PipeWire)
    target_compile_definitions(mark-shot PRIVATE HAVE_PIPEWIRE)
    message(STATUS "mark-shot: PipeWire ${PipeWire_VERSION} found, portal screencast capture enabled")
    if(PkgConfig_FOUND)
        pkg_check_modules(EGLPkg QUIET IMPORTED_TARGET egl)
        pkg_check_modules(GLESv2Pkg QUIET IMPORTED_TARGET glesv2)
    endif()
    if(EGLPkg_FOUND AND GLESv2Pkg_FOUND)
        target_link_libraries(mark-shot PRIVATE PkgConfig::EGLPkg PkgConfig::GLESv2Pkg)
        target_compile_definitions(mark-shot PRIVATE HAVE_PIPEWIRE_DMABUF_IMPORT)
        message(STATUS "mark-shot: PipeWire DMA-BUF import enabled")
    else()
        message(STATUS "mark-shot: PipeWire DMA-BUF import disabled; EGL/GLESv2 not found")
    endif()
    if(MARK_SHOT_WITH_LIBPORTAL AND LibPortal_FOUND)
        target_link_libraries(mark-shot PRIVATE PkgConfig::LibPortal)
        target_compile_definitions(mark-shot PRIVATE HAVE_LIBPORTAL)
        message(STATUS "mark-shot: libportal ${LibPortal_VERSION} found, libportal screencast negotiation enabled")
    elseif(MARK_SHOT_WITH_LIBPORTAL)
        message(STATUS "mark-shot: libportal not found, using direct D-Bus portal screencast negotiation")
    else()
        message(STATUS "mark-shot: libportal support disabled, using direct D-Bus portal screencast negotiation")
    endif()
else()
    if(MARK_SHOT_LINUX)
        message(STATUS "mark-shot: PipeWire not found, Wayland scrolling capture falls back to screenshot portal/grim")
    else()
        message(STATUS "mark-shot: Linux screenshot backends disabled on ${CMAKE_SYSTEM_NAME}; using Qt screen capture")
    endif()
endif()
